# -*- coding: utf-8 -*-
{
    'name': "tx_hr",
    'version': '0.1',
    'depends': ['base', 'hr', 'hr_contract', 'base_tier_validation', 'calendar'],

    'data': [
        # 'data/ir_scheduling_data.xml',
        'security/ir.model.access.csv',
        'views/tx_hr_leave_view.xml',
        'views/tx_hr_overtime_rate.xml',
        'views/tx_hr_performance_application_view.xml',
        'views/tx_hr_other_subsidy_view.xml',
        'views/tx_hr_piece_rate_view.xml',
        'views/tx_hr_overtime_view.xml',
        'views/tx_hr_scheduling_view.xml',
        'views/tx_hr_attendance_view.xml',
        'views/tx_hr_salary_calculation.xml',
        'views/tx_hr_attendance_daily_view.xml',
        'views/tx_hr_attendance_monthly_view.xml',
        'views/tx_hr_holiday_calculation.xml',
        'views/tx_hr_ref_contract.xml',
        'views/tx_hr_ref_employee.xml',
        'views/tx_hr_piecework_type.xml',
        'views/tx_hr_social_security.xml',
        'views/tx_hr_individual_income_tax.xml',
        'views/tx_hr_business_trip_view.xml',
        'views/tx_hr_performance_coefficient_person.xml',
        'views/tx_hr_full_member_person.xml',
        'views/tx_hr_full_person_view.xml',
        'views/tx_hr_piece_rate_person.xml',
        'views/tx_hr_other_subsidy_person.xml',
        'views/tx_hr_withhold_person.xml',
        'views/tx_hr_withhold_view.xml',
        'views/tx_hr_depart_view.xml',
        'views/tx_hr_interview_application_view.xml',
        'views/tx_hr_classes.xml',
        'views/tx_hr_filling_factor.xml',
        'views/tx_hr_card_replacement_application_person.xml',
        'views/tx_hr_card_replacement_application_view.xml',
        'views/tx_hr_card_time_range.xml',
        'views/tx_hr_view.xml',
    ],
    'application': True
}
